spring.application.name=Role Based Access Control

server.servlet.context-path=/api


spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
spring.datasource.username=postgres
spring.datasource.password=immathebest123

spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.properties.hiberate.format_sql=false

jwt.secretKey=SMDIJILS,EWIE2I[Plkmei3y4r734yrdnqwmdlw3ruy3ur

logging.level.org.springframework.security=DEBUG


